### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'ckpt.pt'

### ISSUE THREAD

**Issue by muzihuole** [thuhcsi/adsv_voting#1]
Hello! Thanks for your code first.
I try to run this code, but i find a issue. When I run "stage 2: ASV model evaluation in raw audio", it is as that :
`./run.sh
resnet num_channels: [1, 32, 64, 128, 256]
n_mels: 80
embedding_dim: 256
pooling_type: TSP
Traceback (most recent call last):
  File "tools/evaluate.py", line 25, in <module>
    state_dict = torch.load(cfg.checkpoint_path, map_location="cpu")["state_dict"]
  File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'ckpt.pt'`
I can't find where is the 'ckpt.pt'. Can you help me ?
Looking forward to your reply. Thank you.

**Comment by kabrate** [comment]
我跑的时候是不需要这个文件的。
